name: boxes
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - python=3.6.7
  - pytorch=1.3.1
  - torchvision=0.4.2
  - numpy=1.16.4
  - pillow=6.2.1
  - scipy=1.4.1
  - h5py
  - pip
  - pip:
    - pytorch-lightning==0.7.6